library(tidyverse)
library(xlsx)
# setwd("//sharepoint.fda.gov/DavWWWRoot/orgs/CDRH-QM/QMOE/Shared Documents")
setwd("//sharepoint.fda.gov/DavWWWRoot/orgs/CDRH-QM/Performance/CARS")
css_dir <- getwd()
css_data <- read.csv('cdrh_cs_raw_data_dec_2019_present.csv', header=TRUE, stringsAsFactors=FALSE)
css_data <- rename(css_data, Org.ID = Organization.ID)
cdrh_orgs <- read.csv('cdrh_orgs.csv', header=TRUE, stringsAsFactors=FALSE)
test <- left_join(css_data, cdrh_orgs, by = 'Org.ID')
